---
#
# Playbook to install the ELK stack
#

- hosts: localhost
  remote_user: root
  roles:
    - { role: elasticsearch }
    - { role: logstash, when: ((logging_backend is none) or (logging_backend == 'logstash')) }
    - { role: nginx }
    - { role: kibana }
